# Generated by Django 5.0.6 on 2024-06-25 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('', '---'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não-binário', 'Não-binário'), ('Gênero fluído', 'Gênero fluído'), ('Transgênero masculino', 'Transgênero masculino'), ('Transgênero feminino', 'Transgênero feminino'), ('Outro', 'Outro')], default='', max_length=255)),
                ('sex', models.CharField(choices=[('', '---'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='', max_length=255)),
                ('eye_color', models.CharField(choices=[('', '---'), ('Castanho', 'Castanho'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Cinza', 'Cinza'), ('Outra', 'Outra')], default='', max_length=255)),
                ('ethnicity', models.CharField(choices=[('', '---'), ('Branco', 'Branco'), ('Negro', 'Negro'), ('Asiático', 'Asiático'), ('Indígena', 'Indígena'), ('Pardo', 'Pardo'), ('Outro', 'Outro')], default='', max_length=255)),
                ('height', models.FloatField()),
                ('hair_color', models.CharField(choices=[('', '---'), ('Preto', 'Preto'), ('Castanho escuro', 'Castanho escuro'), ('Castanho médio', 'Castanho médio'), ('Castanho claro', 'Castanho claro'), ('Loiro escuro', 'Loiro escuro'), ('Loiro médio', 'Loiro médio'), ('Loiro claro', 'Loiro claro'), ('Ruivo', 'Ruivo'), ('Outra', 'Outra')], default='', max_length=255)),
                ('blood_type', models.CharField(choices=[('', '---'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=255)),
                ('continuous_medication', models.BooleanField(default=False)),
                ('medication', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('', '---------------'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=2)),
                ('birthmark', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
