# Generated by Django 5.0.6 on 2024-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='scar',
            name='has_scar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='has_tattoo',
            field=models.BooleanField(default=False),
        ),
    ]
